spring.application.name=SistemaGestaoEscolar

#Porta do servidor
server.port=8080

# Configuracao da base de dados (PostgreSQL)	
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#Jpa/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway/migrations
spring.flyway.enabled=true

#Erros
server.error.include-stacktrace=never
server.error.include-message=never
server.error.whitelabel.enabled=false
